# Proxy (Upstream) Server
bindAddress: "0.0.0.0"
port: 25565
motd: "Barrel Proxy\nConnect to Bedrock Server"
# max players in proxy
maxplayers: 10
# proxy icon
icon: "https://raw.githubusercontent.com/BarrelMC/Assets/master/logo/barrel.png"

# Downstream server (bedrock)
bedrockAddress: "play.venitymc.com"
bedrockPort: 19132
# Use xbox login? (offline|online)
auth: online
