# Proxy (Upstream) Server
bindAddress: "0.0.0.0"
port: 25565
motd: "Barrel Proxy\nConnect to Bedrock Server"
# max players in proxy
maxplayers: 10
# proxy icon
icon: "https://raw.githubusercontent.com/BarrelMC/Assets/master/logo/barrel.png"
# Message when the proxy is closed
shutdownMessage: "Proxy Closed"
# Is Player Java Premium
premiumPlayerJava: false

# Downstream server (bedrock)
bedrockAddress: "join.servermc.xyz"
bedrockPort: 10171
# Use xbox login? (offline|online)
auth: online
